package professional.service.corporate.com.atcleaningapp;

import com.paypal.android.sdk.payments.PayPalConfiguration;
import com.paypal.android.sdk.payments.PayPalPayment;

public class URLs {
    public static final String PAYPAL_CLIENT_ID = "AWnFiPdoAaZp0EWLivfnSwl3S8nqQxStI2ax5EFCZbgSBorXjsf4KX07EzGKJY_lVTuSq6El4M17fxkx";
    public static final String PAYPAL_CLIENT_SECRET = "EE1qEzKyyulPFD48cD0JW6lJ3Y98Nv1Q7J8hw7yknhs4f4ayGCqjeBITrLiD3NVIgdpBGyDllstFeCBp";

    public static final String PAYPAL_ENVIRONMENT = PayPalConfiguration.ENVIRONMENT_SANDBOX;
    public static final String PAYMENT_INTENT = PayPalPayment.PAYMENT_INTENT_SALE;
    public static final String DEFAULT_CURRENCY = "CAD";
    public static final String URL_LOGIN = "http://urzom.com/androidapp/index.php/login";
    public static final String URL_REGISTER = "http://urzom.com/androidapp/index.php/register";
    public static final String URL_DOCTOR_LIST = "http://takemytoken.com/AndroidApp/index.php/doctor_list";
    public static final String URL_AVAILABLE_TOKEN_LIST = "http://takemytoken.com/AndroidApp/index.php/get_available_token";
    public static final String URL_ASSIGN_TOKEN_TO_PATIENT = "http://takemytoken.com/AndroidApp/index.php/assign_token_to_patient";
    public static final String URL_PATIENT_LIST = "http://takemytoken.com/AndroidApp/index.php/patient_list";
    public static final String URL_START_SEEING_PATIENT = "http://takemytoken.com/AndroidApp/index.php/update_seeing_status";
    public static final String URL_FINISH_SEEING_PATIENT = "http://takemytoken.com/AndroidApp/index.php/finish_seeing_status";
    public static final String URL_UPDATE_DOC_LOGIN = "http://takemytoken.com/AndroidApp/index.php/update_doc_login";
    public static final String URL_MY_APPONTMENTS = "http://takemytoken.com/AndroidApp/index.php/my_appointments";
    public static final String URL_DOCTOR_SERVING_DETAILS = "http://takemytoken.com/AndroidApp/index.php/serving_details";
    public static final String URL_CHECK_RESPONSE = "http://takemytoken.com/AndroidApp/index.php/check_assignment_status";
    public static final String URL_COMPLETED_PATIENT_LIST = "http://takemytoken.com/AndroidApp/index.php/completed_patient_list";
    public static final String URL_DOCTOR_LAST_SERVING_DETAILS = "http://takemytoken.com/AndroidApp/index.php/last_served_token";
    public static final String URL_MY_PROFILE = "http://urzom.com/androidapp/index.php/my_profile";
    public static final String URL_COMPLETED_PATIENT_LIST_EACH_DAY = "http://takemytoken.com/AndroidApp/index.php/completed_patient_list";
    public static final String URL_UPDATE_AVAILABLE_TIME = "http://takemytoken.com/AndroidApp/index.php/update_available_time";
    public static final String URL_UPDATE_TOKEN_DAILY = "http://takemytoken.com/AndroidApp/index.php/update_token_daily";
    public static final String URL_ADD_LOCATION = "http://urzom.com/androidapp/index.php/add_current_location";
    public static final String URL_CURRENT_LOCATION = "http://takemytoken.com/AndroidApp/index.php/current_location";
    public static final String URL_REGISTER_USER = "http://urzom.com/androidapp/index.php/register_users";
    public static final String URL_ANNOUNCING_PATIENTS = "http://takemytoken.com/AndroidApp/index.php/announcing_patients";
    public static final String URL_CONFIRM_PATIENT_NAME = "http://takemytoken.com/AndroidApp/index.php/confirm_patient_name";
    public static final String URL_ASSIGN_TOKEN_TO_PATIENT_FOR_SOMEONE = "http://takemytoken.com/AndroidApp/index.php/assign_token_to_patient_for_someone";
    public static final String URL_AVAILABLE_TIMING = "http://takemytoken.com/AndroidApp/index.php/retrive_available_time";
    public static final String URL_PROFILE_PIC = "http://urzom.com/androidapp/index.php/upload_profile_pic";
    public static final String URL_UPDATE_PROFILE = "http://urzom.com/androidapp/index.php/update_profile";
    public static final String URL_COMPLETED_WORKS = "http://urzom.com/androidapp/index.php/contractors_day_history";
    public static final String URL_SEND_EMAIL = "http://urzom.com/androidapp/index.php/reset_pass";
    public static final String URL_DOC_APPONTMENTS = "http://takemytoken.com/AndroidApp/index.php/doc_appointments";
    public static final String URL_DOCTOR_LIST_BY_SEARCH = "http://takemytoken.com/AndroidApp/index.php/search_doctors";
    public static final String URL_POST = "http://urzom.com/androidapp/index.php/create_post";
    public static final String URL_JOBS_BY_ME = "http://urzom.com/androidapp/index.php/jobs_created_by_me";
    public static final String URL_JOB_VIEW_FOR_CONTRACTR = "http://urzom.com/androidapp/index.php/job_view_for_contractor";
    public static final String URL_POST_BID = "http://urzom.com/androidapp/index.php/create_a_bid";
    public static final String URL_ALL_AVAIAILBLE_JOBS = "http://urzom.com/androidapp/index.php/show_all_avialble_works";
    public static final String URL_JOB_VIEW_FOR_EMPLOYER = "http://urzom.com/androidapp/index.php/job_view_for_employer";
    public static final String URL_BIDS_FOR_PERTICULAR_PROJECT = "http://urzom.com/androidapp/index.php/bid_response_for_project";
    public static final String URL_ASSIGN_WORK = "http://urzom.com/androidapp/index.php/assign_work";
    public static final String URL_DELETE_WORK = "http://urzom.com/androidapp/index.php/delete_work";
    public static final String URL_ADD_ADDRESS = "http://urzom.com/androidapp/index.php/add_address";
    public static final String URL_ACCEPT_OR_REJECT_WORK = "http://urzom.com/androidapp/index.php/accept_and_reject_work";
    public static final String URL_DELETE_WORK_BY_ME = "http://urzom.com/androidapp/index.php/delete_work_by_me";
    public static final String URL_ALL_AWARDED_WORKS = "http://urzom.com/androidapp/index.php/all_projects_awarded_to_me";
    public static final String URL_ACCEPT_OR_REJECT_OFFER = "http://urzom.com/androidapp/index.php/accept_and_reject_offer";
    public static final String URL_JOBS_BY_ME_COMPLETED_BY_CONTRACTOR = "http://urzom.com/androidapp/index.php/completed_works_by_contractor";
    public static final String URL_JOBS_BY_ME_ONGOING_BY_CONTRACTOR = "http://urzom.com/androidapp/index.php/ongoing_works_by_contractor";
    public static final String URL_JOBS_BY_ME_ONGOING_BY_EMPLOYER = "http://urzom.com/androidapp/index.php/ongoing_works_by_employer";
    public static final String URL_JOBS_BY_ME_COMPLETED_BY_EMPLOYER = "http://urzom.com/androidapp/index.php/completed_works_by_employer";
    public static final String URL_ACCEPT_WORK_OFFER = "http://urzom.com/androidapp/index.php/accept_awarded_work";
    public static final String URL_DELETE_WORK_OFFER = "http://urzom.com/androidapp/index.php/reject_awarded_work";
    public static final String URL_DELETE_PROPOSAL = "http://urzom.com/androidapp/index.php/reject_particular_bid";
    public static final String URL_BIDS_BY_ME = "http://urzom.com/androidapp/index.php/all_bids_by_me";
    public static final String URL_RETRIEVE_ONGOING_PROJECT_DETAILS = "http://urzom.com/androidapp/index.php/retrieve_details_of_project";
    public static final String URL_SEND_PROJECT_COMPLETION_REQUEST_TO_EMPLOYER = "http://urzom.com/androidapp/index.php/send_completion_request";
    public static final String URL_CHECK_IF_BID_POSSIBLE = "http://urzom.com/androidapp/index.php/check_if_bid_possible";
    public static final String GRID_IMAGES_ATTACHED = "http://urzom.com/androidapp/index.php/grid_images_attached";
    public static final String URL_UPDATE_ADDRESS_FOR_PROJECT = "http://urzom.com/androidapp/index.php/update_address";
    public static final String URL_GET_ADDRESS_LIST_FOR_USER = "http://urzom.com/androidapp/index.php/get_address_list";
    public static final String URL_MY_CREATED_PROJECT = "http://urzom.com/androidapp/index.php/get_created_project";
    public static final String URL_CREATE_POST_UPDATE = "http://urzom.com/androidapp/index.php/create_update_post";;
    public static final String URL_SEND_PROJECT_APPROVAL_REQUEST_TO_CONTRACTOR ="http://urzom.com/androidapp/index.php/send_project_completion_approval";
    public static final String URL_RATING = "http://urzom.com/androidapp/index.php/rate_contractor";
    public static final String URL_SHOW_CONTRACTOR_DETAILS = "http://urzom.com/androidapp/index.php/contractor_details";
    public static final String URL_DELETE_WORK_IF_NOT = "http://urzom.com/androidapp/index.php/delete_if_available";
    public static final String URL_MY_PROFILE_C = "http://urzom.com/androidapp/index.php/my_profile_c";
    public static final String URL_JOBS_BID_AMOUNT = "http://urzom.com/androidapp/index.php/create_safe_deposit";
    public static final String URL_SEND_PAYOUT =  "http://urzom.com/androidapp/index.php/send_payout";
    public static final String URL_GET_PAYEE = "http://urzom.com/androidapp/index.php/get_recepient";
}